# Generated by Django 5.0.1 on 2025-10-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
