# Generated by Django 5.0.1 on 2025-11-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_options_alter_user_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailverificationcode",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Email Verification Code",
                "verbose_name_plural": "Email Verification Codes",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterModelTable(
            name="emailverificationcode",
            table="email_verification_codes",
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
